# docker-compose.yml
version: '3.8'
services:
  django:
    build: .
    container_name: chat_django
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    env_file:
      - .env
    command: ./entrypoint.sh

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
