version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_django
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    networks:
      - app-network
    environment:
      DB_NAME: chatdb          # <<< nouvelle base de données
      DB_USER: server
      DB_PASSWORD: 4734
      DB_HOST: mysql
      DB_PORT: 3306
    command: >
      bash -c "until nc -z -v -w30 mysql 3306;
      do echo 'Waiting for MySQL...'; sleep 1; done;
      python manage.py runserver 0.0.0.0:8000"

networks:
  app-network:
    external: true
