version: '3.8'

services:
  django:
    build: .
    container_name: chat_django
    restart: unless-stopped
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - chatnet

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - chatnet

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  chatnet:
