version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_django
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    env_file:
      - .env  # ✅ Charge les variables depuis .env
    command: >
      bash -c "until nc -z -v -w30 $DB_HOST $DB_PORT;
      do echo 'Waiting for MySQL...'; sleep 1; done;
      python manage.py runserver 0.0.0.0:8000"
