# Generated by Django 5.2 on 2026-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_savedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ai_response',
            field=models.BooleanField(default=False),
        ),
    ]
