name: CI/CD Django Docker App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      env:
        ENV_CONTENT: ${{ secrets.ENV_CONTENT }}
      run: echo "$ENV_CONTENT" > .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: your-dockerhub-username/chat-django-app:latest

    - name: Create directory and copy .env to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "$SSH_PRIVATE_KEY"
        ssh -o StrictHostKeyChecking=no root@your-vps-ip << 'EOF'
          mkdir -p /var/www/chat-django
        EOF
        scp .env root@your-vps-ip:/var/www/chat-django/.env

    - name: SSH and deploy on VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "$SSH_PRIVATE_KEY"
        ssh -o StrictHostKeyChecking=no root@your-vps-ip << 'EOF'
          docker pull your-dockerhub-username/chat-django-app:latest
          docker stop chat-django-app || true
          docker rm chat-django-app || true
          docker run -d --name chat-django-app -p 8000:8000 --env-file /var/www/chat-django/.env your-dockerhub-username/chat-django-app:latest
        EOF
